server:
  port: 8080
spring:
  application:
    name: "CrediYaAuth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: ${DB_HOST}
    port: 5432
    database: ${DB_NAME}
    schema: ${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"